// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/employee": {
            "post": {
                "description": "创建员工",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "员工"
                ],
                "summary": "创建员工",
                "parameters": [
                    {
                        "description": "员工信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.EmployeeCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/employee/login": {
            "post": {
                "description": "通过用户名和密码登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "员工"
                ],
                "summary": "员工登录",
                "parameters": [
                    {
                        "description": "登录凭证",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.EmployeeLoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "req.EmployeeCreateReq": {
            "type": "object",
            "required": [
                "id",
                "idNumber",
                "name",
                "phone",
                "sex",
                "username"
            ],
            "properties": {
                "id": {
                    "description": "ID 字段为自增且后端生成",
                    "type": "integer",
                    "example": 1
                },
                "idNumber": {
                    "description": "身份证号：必填 + 18位 + 基础正则（支持末尾X/x）",
                    "type": "string",
                    "example": "110105199003078888"
                },
                "name": {
                    "type": "string",
                    "example": "张三"
                },
                "phone": {
                    "description": "手机号：必填 + 11位 + 大陆手机号正则",
                    "type": "string",
                    "example": "13800000000"
                },
                "sex": {
                    "description": "性别：限制枚举值",
                    "type": "string",
                    "enum": [
                        "男",
                        "女"
                    ],
                    "example": "男"
                },
                "username": {
                    "description": "用户名：必填，唯一",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "req.EmployeeLoginReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "编码：1成功，0和其它数字为失败",
                    "type": "integer",
                    "example": 1
                },
                "data": {
                    "description": "数据",
                    "type": "object"
                },
                "msg": {
                    "description": "错误信息",
                    "type": "string",
                    "example": "success"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "苍穹外卖",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
